import torch.optim

DATAPOINT_SIZE = 100
LATENT_SIZE = 1
BETA = 0.
REGULARIZATION_WEIGHT = 1e4
LEARNING_RATE = 1e-4
OPTIM = torch.optim.Adam

NUM_EPOCHS = 100
BATCH_SIZE = 512

DATA_VARIANCE_SCALE = 5
# INIT_STD = DATA_VARIANCE_SCALE

NUM_TRAIN = 10000
NUM_TEST = 50000
LOAD_DATASET = True
